openapi: 3.0.0
info:
  title: Contoso Real Estate Listings Service
  version: '2023-09-06'
  description: This is the Contoso Real Estate portal listings service
tags:
  - name: listing
paths:
  /listings:
    get:
      tags:
        - listing
      operationId: Listings_list
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Listing'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /listings/{id}:
    get:
      tags:
        - listing
      operationId: Listings_read
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listing'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Address:
      type: object
      properties:
        type:
          type: object
          properties: {}
        description:
          type: string
          enum:
            - A valid address for listing
        id:
          type: string
        slug:
          type: string
        buildingNumber:
          type: string
        street:
          type: string
        city:
          type: string
        zipCode:
          type: string
        country:
          type: string
        createdAt:
          type: object
          properties:
            type:
              type: string
            format:
              type: string
              enum:
                - date-time
          required:
            - type
            - format
        state:
          type: string
      required:
        - type
        - description
        - id
        - slug
        - buildingNumber
        - street
        - city
        - zipCode
        - country
        - createdAt
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message
    Listing:
      type: object
      properties:
        id:
          type: object
          properties:
            type:
              type: string
            format:
              type: string
              enum:
                - uuid
            description:
              type: string
              enum:
                - Autogenerated unique identifier for the listing
            example:
              type: string
              enum:
                - 1db1f3a89eb2dde64e827aea
          required:
            - type
            - format
            - description
            - example
          readOnly: true
        title:
          type: string
        slug:
          type: string
        createdAt:
          type: object
          properties:
            type:
              type: string
            format:
              type: string
              enum:
                - date-time
          required:
            - type
            - format
        bathrooms:
          type: integer
          format: int32
        bedrooms:
          type: integer
          format: int32
        description:
          type: string
        type:
          type: string
        isFeatured:
          type: boolean
        isRecommended:
          type: boolean
        photos:
          type: array
          items:
            type: string
        capacity:
          type: integer
          format: int32
        ammenities:
          type: object
          properties:
            type:
              type: array
              items:
                type: string
            description:
              type: string
              enum:
                - Identifies ammenities in a listing
            items:
              type: object
              properties:
                type:
                  $ref: '#/components/schemas/ammenities'
                default:
                  type: array
                  items: {}
                example:
                  type: array
                  items: {}
              required:
                - type
                - default
                - example
          required:
            - type
            - description
            - items
        reviews:
          type: object
          properties:
            type:
              type: array
              items:
                type: string
            description:
              type: string
              enum:
                - listing reviews
            items:
              type: object
              properties:
                $ref:
                  type: string
                  enum:
                    - '#/components/schemas/Review'
                example:
                  type: array
                  items: {}
              required:
                - $ref
                - example
          required:
            - type
            - description
            - items
        address:
          type: object
          properties:
            type:
              type: object
              properties: {}
            description:
              type: string
              enum:
                - A valid address for listing
            $ref:
              type: string
              enum:
                - '#/components/schemas/Address'
            example:
              type: object
              properties:
                city:
                  type: string
                  enum:
                    - Edinburgh
                country:
                  type: string
                  enum:
                    - Scotland
                street:
                  type: string
                  enum:
                    - Sojourner Drive
                buildingNumber:
                  type: string
                  enum:
                    - Apt 3B
                zipCode:
                  type: string
                  enum:
                    - '10001'
              required:
                - city
                - country
                - street
                - buildingNumber
                - zipCode
          required:
            - type
            - description
            - $ref
            - example
        fees:
          type: object
          properties: {}
      required:
        - title
        - slug
        - bathrooms
        - bedrooms
        - description
        - photos
        - address
    Review:
      type: object
      properties:
        type:
          type: object
          properties: {}
        description:
          type: string
          enum:
            - A valid review for listing
        id:
          type: string
        slug:
          type: string
        userId:
          type: string
        listingId:
          type: string
        rating:
          type: integer
          format: int32
        comment:
          type: string
      required:
        - type
        - description
        - userId
        - listingId
        - rating
        - comment
    ammenities:
      type: string
      enum:
        - swimming pool
        - gym
        - wi-fi
        - parking
        - balcony
        - terrace
        - garden
        - patio
        - sauna
        - jacuzzi
        - fireplace
        - air conditioning
        - heating
        - elevator
        - laundry room
        - dishwasher
        - microwave
        - furniture
        - no furniture
servers:
  - url: http://localhost:7071/api
    description: Localhost Development Endpoint
    variables: {}
  - url: /api
    description: Contoso Azure Hosted Production Endpoint
    variables: {}
