openapi: 3.0.0
info:
  title: Contoso Real Estate Listings Service
  version: '2023-09-06'
  description: This is the Contoso Real Estate portal listings service
tags:
  - name: Listings
paths:
  /api/getListings:
    get:
      tags:
        - Listings
      operationId: Listings_list
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Listing'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/getListings/{id}:
    get:
      tags:
        - Listings
      operationId: Listings_read
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listing'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message
    Listing:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        title:
          type: string
        slug:
          type: string
        createdAt:
          type: string
        bathrooms:
          type: integer
          format: int32
        bedrooms:
          type: integer
          format: int32
        description:
          type: string
        type:
          type: string
        isFeatured:
          type: boolean
        isRecommended:
          type: boolean
        photos:
          type: array
          items:
            type: string
        capacity:
          type: integer
          format: int32
        ammenities:
          type: array
          items:
            type: string
        reviews_stars:
          type: integer
          format: int32
        reviews_int32:
          type: integer
          format: int32
        address:
          type: array
          items:
            type: string
        fees:
          type: array
          items:
            type: string
        $$isFavorited:
          type: boolean
      required:
        - id
        - title
        - slug
        - createdAt
        - bathrooms
        - bedrooms
        - description
        - type
        - isFeatured
        - isRecommended
        - photos
        - capacity
        - ammenities
        - reviews_stars
        - reviews_int32
        - address
        - fees
servers:
  - url: https://{provisionedUrl}.com
    description: Contoso Azure Provisioned Url
    variables:
      provisionedUrl:
        default: ''
        description: This provisioned url should come from env vars
